title: Data 1: Amsterdam
description: Group 5 Assignment results
theme: Iepe

url: https://iepebouw.github.io/iepebouw

aux_links:
  Template Repository: https://github.com/iepebouw/iepebouw

favicon_ico: "assets/images/icons8-1-16.png"
